#!/usr/bin/env python3
"""Regenerate the character-class tables embedded in src/unicode.zig.

Data source: the Unicode Character Database as exposed by Python's
`unicodedata` module (a Unicode-standard data source). This is the same data
the CommonMark spec's character classes reference; it is *not* derived from
any parser implementation.

CommonMark 0.31.2 §2.1 defines:
- Unicode whitespace: the Zs general category, or tab (U+0009), line feed
  (U+000A), form feed (U+000C), or carriage return (U+000D).
- Unicode punctuation: the P (punctuation) or S (symbol) general categories.

It also emits a Unicode *full case folding* table (the same data the
CommonMark spec's label matching uses: "perform the Unicode case fold",
§6.6; `[ẞ]` matches `[SS]`, which only the full fold gives). Python's
`str.casefold()` implements the UCD's full case folding (CaseFolding.txt,
statuses C+F). The table holds every code point whose fold differs from
itself; entries are (code point, 1-3 folded code points).

In addition to the combined P+S punctuation table (CommonMark §2.1), it
emits a P-only table (the P general categories: Pc/Pd/Pe/Pf/Pi/Po/Ps) for
the Cooklang frontend, whose word boundaries follow the Cooklang EBNF
(`punctuation character = ? Unicode General Category P* ?`) — the
canonical corpus's `@🧂` (So, a symbol) requires symbols to stay inside
single-word names.

The script emits the two sorted, merged, inclusive range lists and the fold
table as flat arrays of `u21` values. Run `python3 tools/gen-unicode.py`
and paste the output into src/unicode.zig (or use the --file flag to write
it), then run `zig fmt src/unicode.zig` to normalize formatting.
"""

import argparse
import unicodedata

MAX_CP = 0x110000


def ranges_for(pred):
    out = []
    start = None
    end = None
    for cp in range(MAX_CP):
        if pred(cp):
            if start is None:
                start = cp
            end = cp
        else:
            if start is not None:
                out.append((start, end))
                start = None
    if start is not None:
        out.append((start, end))
    return out


def merge(rs):
    out = []
    for start, end in sorted(rs):
        if out and start <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], end))
        else:
            out.append((start, end))
    return out


def emit(name, ranges):
    lines = [f"/// {name}: {len(ranges)} ranges, {sum(e - s + 1 for s, e in ranges)} code points."]
    lines.append(f"const {name} = [_]u21{{")
    row = []
    for start, end in ranges:
        row.append(f"0x{start:X}, 0x{end:X},")
        if len(row) == 4:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("};")
    return "\n".join(lines)


def emit_folds():
    """Every code point whose full case fold differs from itself, as flat
    [cp, len, c0, c1, c2] u21 entries (unused trailing chars are 0)."""
    entries = []
    for cp in range(MAX_CP):
        folded = chr(cp).casefold()
        if folded != chr(cp):
            chars = [ord(c) for c in folded]
            if not (1 <= len(chars) <= 3):
                raise AssertionError((hex(cp), chars))
            entries.append((cp, chars))
    lines = [f"/// {len(entries)} entries: code points whose full case fold differs from themselves."]
    lines.append("const casefold_entries = [_]u21{")
    row = []
    for cp, chars in entries:
        # Fixed 5-slot layout: [cp, len, c0, c1, c2] with zero padding, so
        # the lookup can stride by 5 and binary-search on cp.
        n = len(chars)
        chars = chars + [0] * (3 - n)
        row.append(f"0x{cp:X}, {n}, " + ", ".join(f"0x{c:X}" for c in chars) + ",")
        if len(row) == 2:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", metavar="PATH", help="write tables to this file")
    args = ap.parse_args()

    whitespace = merge(
        ranges_for(lambda cp: unicodedata.category(chr(cp)) == "Zs")
        + [(0x09, 0x09), (0x0A, 0x0A), (0x0C, 0x0C), (0x0D, 0x0D)]
    )
    # P and S are category-group prefixes: Pc/Pd/Pe/Pf/Pi/Po/Ps and
    # Sc/Sk/Sm/So. Compare the leading character of the two-letter code.
    punctuation = ranges_for(lambda cp: unicodedata.category(chr(cp))[0] in "PS")
    # P only (no symbols): Cooklang's EBNF word boundaries stop at P*, and
    # the canonical corpus requires symbols like So to stay in names.
    punctuation_p = ranges_for(lambda cp: unicodedata.category(chr(cp))[0] == "P")

    header = (
        "// Generated by tools/gen-unicode.py — do not edit by hand.\n"
        f"// Unicode data version: {unicodedata.unidata_version}.\n"
    )
    out = (
        header
        + "\n"
        + emit("whitespace_ranges", whitespace)
        + "\n\n"
        + emit("punctuation_ranges", punctuation)
        + "\n\n"
        + emit("punctuation_p_ranges", punctuation_p)
        + "\n\n"
        + emit_folds()
        + "\n"
    )

    if args.file:
        with open(args.file, "w", encoding="utf-8") as f:
            f.write(out)
        print(f"wrote {args.file}")
    else:
        print(out)


if __name__ == "__main__":
    main()
